funFacts:
  "Listening To":
    href: https://www.youtube.com/watch?v=UKvjXQJZJQ8
    text: Fanfare by Advantage Lucy
  "I Recommend Reading:":
    href: https://effroncenter.princeton.edu/about/bookshelf/ornamentalism
    text: "ORNAMENTALISM by Anne Anlin Cheng"
  "See how this site was built 👀":
    href: https://github.com/codelastnight/portfolio2
    text: Github Source
  "Find Me Also":
    href: https://artsandcraft.work
    text: Studio Arts+Crafts
