funFacts:
  "Listening To":
    href: https://www.youtube.com/watch?v=qvUw3tv-gVk
    text: Five Years of Work and We Built That Song by Newfound Interest in Connecticut
  "Reading Right Now":
    href: https://www.sternberg-press.com/product/para-platforms-on-the-spatial-politics-of-right-wing-populism/
    text: "Para-Platforms: On the Spatial Politics of Right-Wing Populism. MARKUS MIESSEN, ZOË RITTS (EDS.)"
  "See how this site was built 👀":
    href: https://github.com/codelastnight/portfolio2
    text: Github Source
