funFacts:
  "Listening To":
    href: https://www.youtube.com/watch?v=8cUSDE8ZySc
    text: Cardboard Boxes by twikipedia
  "Reading Right Now":
    href: https://www.sternberg-press.com/product/para-platforms-on-the-spatial-politics-of-right-wing-populism/
    text: "Para-Platforms: On the Spatial Politics of Right-Wing Populism. MARKUS MIESSEN, ZOË RITTS (EDS.)"
  "See how this site was built 👀":
    href: https://github.com/codelastnight/portfolio2
    text: Github Source
